// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestaurantManagerApp.Models;

namespace RestaurantManager.Migrations
{
    [DbContext(typeof(AdvDatabaseProjectContext))]
    partial class AdvDatabaseProjectContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RestaurantManagerApp.Models.Customers", b =>
                {
                    b.Property<int>("CNum")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("C_NUM")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CAddy")
                        .IsRequired()
                        .HasColumnName("C_ADDY")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<int>("CCcnum")
                        .HasColumnName("C_CCNUM");

                    b.Property<string>("CEmail")
                        .IsRequired()
                        .HasColumnName("C_EMAIL")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("CFname")
                        .IsRequired()
                        .HasColumnName("C_FNAME")
                        .HasMaxLength(45)
                        .IsUnicode(false);

                    b.Property<string>("CLname")
                        .IsRequired()
                        .HasColumnName("C_LNAME")
                        .HasMaxLength(45)
                        .IsUnicode(false);

                    b.HasKey("CNum");

                    b.HasIndex("CEmail")
                        .IsUnique()
                        .HasName("C_EMAIL_UNIQUE");

                    b.ToTable("CUSTOMERS");
                });

            modelBuilder.Entity("RestaurantManagerApp.Models.EmployeeInfo", b =>
                {
                    b.Property<int>("ENum")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("E_NUM")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ELevel")
                        .HasColumnName("E_LEVEL");

                    b.Property<string>("EName")
                        .IsRequired()
                        .HasColumnName("E_NAME")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.HasKey("ENum");

                    b.ToTable("EMPLOYEE_INFO");
                });

            modelBuilder.Entity("RestaurantManagerApp.Models.Inventory", b =>
                {
                    b.Property<int>("InvNum")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("INV_NUM")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("InvDesc")
                        .IsRequired()
                        .HasColumnName("INV_DESC")
                        .HasMaxLength(150)
                        .IsUnicode(false);

                    b.Property<int>("InvPar")
                        .HasColumnName("INV_PAR");

                    b.Property<int>("InvQoh")
                        .HasColumnName("INV_QOH");

                    b.HasKey("InvNum");

                    b.ToTable("INVENTORY");
                });

            modelBuilder.Entity("RestaurantManagerApp.Models.Items", b =>
                {
                    b.Property<int>("ItemNum")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ITEM_NUM")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ItemDesc")
                        .HasColumnName("ITEM_DESC")
                        .HasMaxLength(200)
                        .IsUnicode(false);

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnName("ITEM_NAME")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<decimal>("ItemPrice")
                        .HasColumnName("ITEM_PRICE")
                        .HasColumnType("decimal(18, 0)");

                    b.HasKey("ItemNum");

                    b.ToTable("ITEMS");
                });

            modelBuilder.Entity("RestaurantManagerApp.Models.Orders", b =>
                {
                    b.Property<int>("ONum")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("O_NUM")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("OApproved");

                    b.Property<int>("OInvNum")
                        .HasColumnName("O_INV_NUM");

                    b.Property<int>("OQuant")
                        .HasColumnName("O_QUANT");

                    b.HasKey("ONum");

                    b.HasIndex("OInvNum");

                    b.ToTable("ORDERS");
                });

            modelBuilder.Entity("RestaurantManagerApp.Models.RecipeLines", b =>
                {
                    b.Property<int>("RlNum")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("RL_NUM")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("RlInvNum")
                        .HasColumnName("RL_INV_NUM");

                    b.Property<int>("RlItemNum")
                        .HasColumnName("RL_ITEM_NUM");

                    b.Property<int>("RlQty")
                        .HasColumnName("RL_QTY");

                    b.HasKey("RlNum");

                    b.HasIndex("RlInvNum");

                    b.HasIndex("RlItemNum");

                    b.ToTable("RECIPE_LINES");
                });

            modelBuilder.Entity("RestaurantManagerApp.Models.ReservationItems", b =>
                {
                    b.Property<int>("RiNum")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("RI_NUM")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("RiItemNum")
                        .HasColumnName("RI_ITEM_NUM");

                    b.Property<int>("RiResNum")
                        .HasColumnName("RI_RES_NUM");

                    b.Property<int?>("RiStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("RI_STATUS")
                        .HasDefaultValueSql("((0))");

                    b.HasKey("RiNum");

                    b.HasIndex("RiItemNum");

                    b.HasIndex("RiResNum");

                    b.HasIndex("RiStatus");

                    b.ToTable("RESERVATION_ITEMS");
                });

            modelBuilder.Entity("RestaurantManagerApp.Models.Reservations", b =>
                {
                    b.Property<int>("RNum")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("R_NUM")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("RCnum")
                        .HasColumnName("R_CNUM");

                    b.Property<DateTime>("RDate")
                        .HasColumnName("R_DATE")
                        .HasColumnType("date");

                    b.Property<decimal?>("RPaid")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("R_PAID")
                        .HasColumnType("decimal(18, 0)")
                        .HasDefaultValueSql("((0.00))");

                    b.Property<decimal?>("RSubtotal")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("R_SUBTOTAL")
                        .HasColumnType("decimal(18, 0)")
                        .HasDefaultValueSql("((0.00))");

                    b.Property<int?>("RTable")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("R_TABLE")
                        .HasDefaultValueSql("((0))");

                    b.Property<TimeSpan>("RTime")
                        .HasColumnName("R_TIME")
                        .HasColumnType("time(6)");

                    b.HasKey("RNum");

                    b.HasIndex("RCnum");

                    b.ToTable("RESERVATIONS");
                });

            modelBuilder.Entity("RestaurantManagerApp.Models.Orders", b =>
                {
                    b.HasOne("RestaurantManagerApp.Models.Inventory", "OInvNumNavigation")
                        .WithMany("Orders")
                        .HasForeignKey("OInvNum")
                        .HasConstraintName("FK_O_INV_NUM");
                });

            modelBuilder.Entity("RestaurantManagerApp.Models.RecipeLines", b =>
                {
                    b.HasOne("RestaurantManagerApp.Models.Inventory", "RlInvNumNavigation")
                        .WithMany("RecipeLines")
                        .HasForeignKey("RlInvNum")
                        .HasConstraintName("FK_RL_INV");

                    b.HasOne("RestaurantManagerApp.Models.Items", "RlItemNumNavigation")
                        .WithMany("RecipeLines")
                        .HasForeignKey("RlItemNum")
                        .HasConstraintName("FK_RL_ITEM");
                });

            modelBuilder.Entity("RestaurantManagerApp.Models.ReservationItems", b =>
                {
                    b.HasOne("RestaurantManagerApp.Models.Items", "RiItemNumNavigation")
                        .WithMany("ReservationItems")
                        .HasForeignKey("RiItemNum")
                        .HasConstraintName("FK_RI_ITEM");

                    b.HasOne("RestaurantManagerApp.Models.Reservations", "RiResNumNavigation")
                        .WithMany("ReservationItems")
                        .HasForeignKey("RiResNum")
                        .HasConstraintName("FK_RI_REV");

                    b.HasOne("RestaurantManagerApp.Models.EmployeeInfo", "RiStatusNavigation")
                        .WithMany("ReservationItems")
                        .HasForeignKey("RiStatus")
                        .HasConstraintName("FK_EMP");
                });

            modelBuilder.Entity("RestaurantManagerApp.Models.Reservations", b =>
                {
                    b.HasOne("RestaurantManagerApp.Models.Customers", "RCnumNavigation")
                        .WithMany("Reservations")
                        .HasForeignKey("RCnum")
                        .HasConstraintName("FK_REF_CUS");
                });
#pragma warning restore 612, 618
        }
    }
}
